/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SignalService } from "../signal.service";
import { SignalCreateInput } from "./SignalCreateInput";
import { Signal } from "./Signal";
import { SignalFindManyArgs } from "./SignalFindManyArgs";
import { SignalWhereUniqueInput } from "./SignalWhereUniqueInput";
import { SignalUpdateInput } from "./SignalUpdateInput";

export class SignalControllerBase {
  constructor(protected readonly service: SignalService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Signal })
  async createSignal(@common.Body() data: SignalCreateInput): Promise<Signal> {
    return await this.service.createSignal({
      data: {
        ...data,

        subscription: data.subscription
          ? {
              connect: data.subscription,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        subscription: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Signal] })
  @ApiNestedQuery(SignalFindManyArgs)
  async signals(@common.Req() request: Request): Promise<Signal[]> {
    const args = plainToClass(SignalFindManyArgs, request.query);
    return this.service.signals({
      ...args,
      select: {
        createdAt: true,
        id: true,

        subscription: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Signal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async signal(
    @common.Param() params: SignalWhereUniqueInput
  ): Promise<Signal | null> {
    const result = await this.service.signal({
      where: params,
      select: {
        createdAt: true,
        id: true,

        subscription: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Signal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSignal(
    @common.Param() params: SignalWhereUniqueInput,
    @common.Body() data: SignalUpdateInput
  ): Promise<Signal | null> {
    try {
      return await this.service.updateSignal({
        where: params,
        data: {
          ...data,

          subscription: data.subscription
            ? {
                connect: data.subscription,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          subscription: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Signal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSignal(
    @common.Param() params: SignalWhereUniqueInput
  ): Promise<Signal | null> {
    try {
      return await this.service.deleteSignal({
        where: params,
        select: {
          createdAt: true,
          id: true,

          subscription: {
            select: {
              id: true,
            },
          },

          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
