/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatGroupCreateNestedManyWithoutSubscriptionsInput } from "./ChatGroupCreateNestedManyWithoutSubscriptionsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CourseCreateNestedManyWithoutSubscriptionsInput } from "./CourseCreateNestedManyWithoutSubscriptionsInput";
import { SignalCreateNestedManyWithoutSubscriptionsInput } from "./SignalCreateNestedManyWithoutSubscriptionsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class SubscriptionCreateInput {
  @ApiProperty({
    required: false,
    type: () => ChatGroupCreateNestedManyWithoutSubscriptionsInput,
  })
  @ValidateNested()
  @Type(() => ChatGroupCreateNestedManyWithoutSubscriptionsInput)
  @IsOptional()
  @Field(() => ChatGroupCreateNestedManyWithoutSubscriptionsInput, {
    nullable: true,
  })
  chatGroups?: ChatGroupCreateNestedManyWithoutSubscriptionsInput;

  @ApiProperty({
    required: false,
    type: () => CourseCreateNestedManyWithoutSubscriptionsInput,
  })
  @ValidateNested()
  @Type(() => CourseCreateNestedManyWithoutSubscriptionsInput)
  @IsOptional()
  @Field(() => CourseCreateNestedManyWithoutSubscriptionsInput, {
    nullable: true,
  })
  courses?: CourseCreateNestedManyWithoutSubscriptionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => SignalCreateNestedManyWithoutSubscriptionsInput,
  })
  @ValidateNested()
  @Type(() => SignalCreateNestedManyWithoutSubscriptionsInput)
  @IsOptional()
  @Field(() => SignalCreateNestedManyWithoutSubscriptionsInput, {
    nullable: true,
  })
  signals?: SignalCreateNestedManyWithoutSubscriptionsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { SubscriptionCreateInput as SubscriptionCreateInput };
