/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SubscriptionService } from "../subscription.service";
import { SubscriptionCreateInput } from "./SubscriptionCreateInput";
import { Subscription } from "./Subscription";
import { SubscriptionFindManyArgs } from "./SubscriptionFindManyArgs";
import { SubscriptionWhereUniqueInput } from "./SubscriptionWhereUniqueInput";
import { SubscriptionUpdateInput } from "./SubscriptionUpdateInput";
import { ChatGroupFindManyArgs } from "../../chatGroup/base/ChatGroupFindManyArgs";
import { ChatGroup } from "../../chatGroup/base/ChatGroup";
import { ChatGroupWhereUniqueInput } from "../../chatGroup/base/ChatGroupWhereUniqueInput";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import { SignalFindManyArgs } from "../../signal/base/SignalFindManyArgs";
import { Signal } from "../../signal/base/Signal";
import { SignalWhereUniqueInput } from "../../signal/base/SignalWhereUniqueInput";

export class SubscriptionControllerBase {
  constructor(protected readonly service: SubscriptionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Subscription })
  async createSubscription(
    @common.Body() data: SubscriptionCreateInput
  ): Promise<Subscription> {
    return await this.service.createSubscription({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Subscription] })
  @ApiNestedQuery(SubscriptionFindManyArgs)
  async subscriptions(@common.Req() request: Request): Promise<Subscription[]> {
    const args = plainToClass(SubscriptionFindManyArgs, request.query);
    return this.service.subscriptions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async subscription(
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Subscription | null> {
    const result = await this.service.subscription({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSubscription(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() data: SubscriptionUpdateInput
  ): Promise<Subscription | null> {
    try {
      return await this.service.updateSubscription({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Subscription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSubscription(
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Subscription | null> {
    try {
      return await this.service.deleteSubscription({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/chatGroups")
  @ApiNestedQuery(ChatGroupFindManyArgs)
  async findChatGroups(
    @common.Req() request: Request,
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<ChatGroup[]> {
    const query = plainToClass(ChatGroupFindManyArgs, request.query);
    const results = await this.service.findChatGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        name: true,

        subscription: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/chatGroups")
  async connectChatGroups(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: ChatGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatGroups: {
        connect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/chatGroups")
  async updateChatGroups(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: ChatGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatGroups: {
        set: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/chatGroups")
  async disconnectChatGroups(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: ChatGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      chatGroups: {
        disconnect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/courses")
  @ApiNestedQuery(CourseFindManyArgs)
  async findCourses(
    @common.Req() request: Request,
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Course[]> {
    const query = plainToClass(CourseFindManyArgs, request.query);
    const results = await this.service.findCourses(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,

        subscription: {
          select: {
            id: true,
          },
        },

        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/courses")
  async connectCourses(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        connect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/courses")
  async updateCourses(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        set: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/courses")
  async disconnectCourses(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: CourseWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      courses: {
        disconnect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/signals")
  @ApiNestedQuery(SignalFindManyArgs)
  async findSignals(
    @common.Req() request: Request,
    @common.Param() params: SubscriptionWhereUniqueInput
  ): Promise<Signal[]> {
    const query = plainToClass(SignalFindManyArgs, request.query);
    const results = await this.service.findSignals(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        subscription: {
          select: {
            id: true,
          },
        },

        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/signals")
  async connectSignals(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: SignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      signals: {
        connect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/signals")
  async updateSignals(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: SignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      signals: {
        set: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/signals")
  async disconnectSignals(
    @common.Param() params: SubscriptionWhereUniqueInput,
    @common.Body() body: SignalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      signals: {
        disconnect: body,
      },
    };
    await this.service.updateSubscription({
      where: params,
      data,
      select: { id: true },
    });
  }
}
